version: "3.8"

services:
  frontend:
    container_name: react-tenfolio-app
    image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      # - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
