version: "3.8"

services:
  frontend:
    container_name: react-tenfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/ReactTenfolio
      - /workspaces/ReactTenfolio/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
